<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function celebr8d8_preprocess_page(&$variables) {
  if ($variables['is_front']) {
    $variables['#attached']['library'][] = 'celebr8d8/home-js';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function celebr8d8_preprocess_node(&$variables) {
  $node = $variables['node'];

  if (isset($node->field_category)) {
    $variables['category_class'] = $node->field_category[0]->target_id;
  }
}
