<?php

/**
 * @file
 * Functions to support theming in the Jackdaw theme.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_preprocess_HOOK() for block templates.
 *
 * Add title and content attributes to blocks.
 */
function jackdaw_preprocess_block(&$variables) {
  $variables['title_attributes']['class'][] = 'block__title';
  $variables['content_attributes']['class'][] = 'block__content';
}
